;;; -*- lexical-binding: t; -*-
(require 'ert)
(require 'tmux-control-scroll-trace)

(ert-deftest tmux-control-trace-test-same-trajectory-at-both-rates ()
  (dolist (hz '(60 120))
    (let ((samples (tmux-control-trace-plan hz)))
      (should (= (length samples) (* 4 hz)))
      (should (= (apply #'+ (mapcar (lambda (s) (plist-get s :delta_px)) samples)) 2400))
      (should (= (plist-get (car samples) :scheduled_ms) 250))
      (should (= (plist-get (nth (* 3 hz) samples) :scheduled_ms) 3750))
      (should (< (plist-get (car (last samples)) :scheduled_ms) 4750)))))

(ert-deftest tmux-control-trace-test-rejects-inexact-rates ()
  (should-error (tmux-control-trace-plan 59))
  (should-error (tmux-control-trace-plan 0)))

(ert-deftest tmux-control-trace-test-catch-up-preserves-inputs-and-deadline ()
  (let* ((samples (tmux-control-trace-plan 60))
         (tmux-control-trace--run (list :epoch 100 :remaining samples))
         (tmux-control-trace--input-timer nil)
         emitted deadline)
    (cl-letf (((symbol-function 'tmux-control-trace--now) (lambda () 300))
              ((symbol-function 'tmux-control-trace--enqueue)
               (lambda (sample) (push (plist-get sample :id) emitted)))
              ((symbol-function 'run-at-time)
               (lambda (time _repeat _function)
                 (should-not deadline)
                 (setq deadline (float-time time))
                 'test-timer)))
      (tmux-control-trace--dispatch-due))
    (should (equal (reverse emitted) '(1 2 3 4)))
    (should (= (length (plist-get tmux-control-trace--run :remaining)) 236))
    (should (< (abs (- deadline (+ 100 (/ (+ 250 (* 4 (/ 1000.0 60))) 1000)))) .000001))))

(ert-deftest tmux-control-trace-test-gc-records-completion-and-increment ()
  (let ((tmux-control-trace--run (list :gc-last 1.0 :gc-events nil))
        (gc-elapsed 1.25))
    (cl-letf (((symbol-function 'tmux-control-trace--now) (lambda () 900))
              ((symbol-function 'backtrace-frames)
               (lambda () '((t garbage-collect private-argument)))))
      (tmux-control-trace--after-gc)
      (setq gc-elapsed 1.30)
      (tmux-control-trace--after-gc))
    (let ((events (reverse (plist-get tmux-control-trace--run :gc-events))))
      (should (= (plist-get (car events) :completion_ms) 900))
      (should (= (plist-get (car events) :gc_ms) 250))
      (should (< (abs (- (plist-get (cadr events) :gc_ms) 50)) .00001))
      (should (equal (plist-get (car events) :stack) ["garbage-collect"])))))

(ert-deftest tmux-control-trace-test-content-coordinate-survives-prepend ()
  (save-window-excursion
    (with-temp-buffer
      (insert "ROW 000101 | content\nROW 000102 | more\n")
      (set-window-buffer (selected-window) (current-buffer))
      (set-window-start nil (point-min))
      (let* ((window (selected-window))
             (tmux-control-trace--run (list :window window :row-height 15))
             (anchor (copy-marker (window-start) t)))
        (should (= (tmux-control-trace--position) 1500))
        (goto-char (point-min))
        (insert "ROW 000100 | older\n")
        (set-window-start window anchor t)
        (should (= (tmux-control-trace--position) 1500))
        (set-marker anchor nil)))))

(ert-deftest tmux-control-trace-test-partial-trimmed-row ()
  (save-window-excursion
    (with-temp-buffer
      (tmux-control-mode)
      (let ((inhibit-read-only t))
        (insert "remaining tail\nROW 000102 | more\n"))
      (set-window-buffer (selected-window) (current-buffer))
      (set-window-start nil (point-min))
      (let ((tmux-control-trace--run
             (list :window (selected-window) :row-height 15 :anchor-kind nil)))
        (should (= (tmux-control-trace--position) 1500))
        (should (equal (plist-get tmux-control-trace--run :anchor-kind)
                       "inferred-next-row"))))))
